### ISSUE TITLE
Unable to switch instances in Firefox

### ISSUE THREAD

**Issue by ghost** [stefanbohacek/mastodon-tools#2]
_Firefox 125.0.2 (64-bit)_
_Mozilla Firefox Snap for Ubuntu_
_canonical-002 - 1.0_

1. Have a toot selected. 
2. Attempting to switch instances, nothing happens:
![different_instance](https://github.com/stefanbohacek/mastodon-tools/assets/54612/5626e268-9916-4d6c-8489-e798fec229f2)
3. Clicking the current instance:
![same_instance](https://github.com/stefanbohacek/mastodon-tools/assets/54612/754c2694-61eb-4df1-bb3b-f6f211a0633a)

**Comment by stefanbohacek** [comment]
@kevinsearle Thank you for reporting this, looking into it!

**Comment by ghost** [comment]
Another thing that I noticed. Going to https://stefanbohacek.online/@stefan/109789908390160370
and attempting to switch to either of my configured instances nothing occurs.

**Comment by stefanbohacek** [comment]
@kevinsearle Okay, found the issue.

https://github.com/stefanbohacek/mastodon-tools/commit/946d78453d3b4d5da0595a40aa2f64a2585eb108

Not too sure if the argument name here changed, but either way, at least it's an easy fix. Thank you, again!
